import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Keypair } from "maci-domainobjs";
import { useEffect, useState } from 'react';


export default function Home() {
  const [ maciKey, setMaciKey ] = useState('')

  useEffect(() => {
    setMaciKey(() => new Keypair().pubKey.serialize())
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>Refresh the page to generate new key...</h2>
        <p className={styles.description}>{maciKey}</p>
      </main>
    </div>
  )
}
